// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organization.API.Context;

namespace Organization.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200817071549_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Organization.API.Model.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DepartmentHeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            DepartmentHeadName = "Alisha",
                            Name = "H.R."
                        },
                        new
                        {
                            Id = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            DepartmentHeadName = "Anika",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("24810dfc-2d94-4cc7-aab5-cdf98b83f0c9"),
                            DepartmentHeadName = "Aayan",
                            Name = "Accounts"
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            DepartmentHeadName = "Bhuvan",
                            Name = "Marketing"
                        });
                });

            modelBuilder.Entity("Organization.API.Model.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b1c2b4d-48c7-402a-80c3-cc796ad49c6b"),
                            ContactNumber = "9999988888",
                            DepartmentId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Zara",
                            Salary = 80000
                        },
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1bea7ee"),
                            ContactNumber = "7777788888",
                            DepartmentId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Alex",
                            Salary = 70000
                        },
                        new
                        {
                            Id = new Guid("d173e20d-159e-4127-9ce9-b0ac2564ad97"),
                            ContactNumber = "9898989898",
                            DepartmentId = new Guid("da2fd609-d754-4feb-8acd-c4f9ff13ba96"),
                            Name = "Tanvi",
                            Salary = 75000
                        },
                        new
                        {
                            Id = new Guid("493c3228-3444-4a49-9cc0-e8532edc59b2"),
                            ContactNumber = "9396939693",
                            DepartmentId = new Guid("24810dfc-2d94-4cc7-aab5-cdf98b83f0c9"),
                            Name = "Shrishti",
                            Salary = 65000
                        },
                        new
                        {
                            Id = new Guid("40ff5488-fdab-45b5-bc3a-14302d59869a"),
                            ContactNumber = "8787898985",
                            DepartmentId = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            Name = "Anant",
                            Salary = 74000
                        });
                });

            modelBuilder.Entity("Organization.API.Model.Employee", b =>
                {
                    b.HasOne("Organization.API.Model.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
